import { describe, expect, test } from "bun:test";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import packageJson from "../../package.json";
import {
  getMobileAboutLinksArrangement,
  estimateMobileAboutSheetContentHeight,
} from "./mobileAboutLayout";
import {
  groupMobileOpenSourceNotices,
  MOBILE_OPEN_SOURCE_APACHE_PACKAGES,
  MOBILE_OPEN_SOURCE_MIT_PACKAGES,
  MOBILE_OPEN_SOURCE_NOTICES,
} from "./mobileOpenSourceLicenses";
import {
  MOBILE_LICENSE_TEXT_APACHE_2_0,
  MOBILE_LICENSE_TEXT_FSL_1_1_MIT,
  MOBILE_LICENSE_TEXT_OFL_1_1,
} from "./mobileOpenSourceLicenseTexts";

const mobileRoot = path.join(import.meta.dir, "../..");

function readText(relative: string): string | null {
  const file = path.join(mobileRoot, relative);
  if (!existsSync(file)) return null;
  return readFileSync(file, "utf8").replace(/\r\n/g, "\n").replace(/^\n+|\n+$/g, "");
}

function notice(id: string) {
  const found = MOBILE_OPEN_SOURCE_NOTICES.find((item) => item.id === id);
  if (!found) throw new Error(`missing notice ${id}`);
  return found;
}

describe("open-source license texts", () => {
  test("ichiran-node's license is the vendored LICENSE, verbatim", () => {
    // ios/Vendor is generated by scripts/vendor-ichiran.sh (gitignored).
    const vendored = readText("modules/nemu-japanese-learning/ios/Vendor/LICENSE-ichiran-node.md");
    if (vendored !== null) expect(MOBILE_LICENSE_TEXT_FSL_1_1_MIT).toBe(vendored);
    expect(MOBILE_LICENSE_TEXT_FSL_1_1_MIT).toStartWith(
      "# Functional Source License, Version 1.1, MIT Future License",
    );
    expect(MOBILE_LICENSE_TEXT_FSL_1_1_MIT).toContain("Copyright 2025 Tiger Tang");
  });

  test("the brand font and Apache notices match the shipped files", () => {
    expect(MOBILE_LICENSE_TEXT_OFL_1_1).toBe(readText("assets/fonts/NemuBrand-LICENSE.txt")!);
    const convex =
      readText("node_modules/convex/LICENSE") ?? readText("../../node_modules/convex/LICENSE");
    if (convex !== null) expect(MOBILE_LICENSE_TEXT_APACHE_2_0).toBe(convex);
  });
});

describe("open-source notices", () => {
  test("credits the EDRDG files as the licence requires", () => {
    const jmdict = notice("jmdict");
    expect(jmdict.license).toBe("CC-BY-SA-4.0");
    expect(jmdict.notice).toContain(
      "These files are the property of the Electronic Dictionary Research and Development Group, and are used in conformance with the Group's licence.",
    );
    expect(jmdict.links.map((link) => link.url)).toContain(
      "https://www.edrdg.org/edrdg/licence.html",
    );
    expect(notice("kanjidic2").license).toBe("CC-BY-SA-4.0");
  });

  test("covers the analyzer, its upstream and its conjugation data", () => {
    expect(notice("ichiran-node").license).toBe("FSL-1.1-MIT");
    expect(notice("ichiran-kernel").license).toBe("MIT");
    expect(notice("ichiran").notice).toBe("Copyright (c) 2014 Timofei Shatrov");
    expect(notice("jmdictdb").license).toBe("GPL-2.0-or-later");
    expect(notice("jmdictdb").licenseText).toContain("GNU GENERAL PUBLIC LICENSE");
  });

  test("lists only packages the app actually depends on", () => {
    const dependencies = new Set(Object.keys(packageJson.dependencies));
    for (const item of [...MOBILE_OPEN_SOURCE_MIT_PACKAGES, ...MOBILE_OPEN_SOURCE_APACHE_PACKAGES]) {
      const first = item.name.split(/[ ,]/)[0]!;
      expect(dependencies.has(first)).toBe(true);
      expect(item.copyright.length).toBeGreaterThan(0);
    }
  });

  test("groups by section and keeps platform-only components on their platform", () => {
    const ios = groupMobileOpenSourceNotices("ios");
    expect(ios.map((group) => group.section)).toEqual(["japaneseAnalysis", "fonts", "software"]);
    const iosIds = ios.flatMap((group) => group.notices.map((item) => item.id));
    const androidIds = groupMobileOpenSourceNotices("android").flatMap((group) =>
      group.notices.map((item) => item.id),
    );
    expect(iosIds).not.toContain("jsc-android");
    expect(androidIds).toContain("jsc-android");
    expect(new Set(iosIds).size).toBe(iosIds.length);
  });
});

describe("About sheet links", () => {
  test("sit side by side in landscape so the sheet keeps its height", () => {
    expect(getMobileAboutLinksArrangement({ width: 874, height: 402 })).toBe("row");
    expect(getMobileAboutLinksArrangement({ width: 402, height: 874 })).toBe("column");
    expect(
      estimateMobileAboutSheetContentHeight({ fontScale: 1, hero: "regular", links: "column" }) -
        estimateMobileAboutSheetContentHeight({ fontScale: 1, hero: "regular", links: "row" }),
    ).toBe(70);
  });
});
