/**
 * Local registry for locally built Tachiyomi extensions.
 * Only enabled in development mode when VITE_TACHIYOMI_LOCAL_PATH is set.
 */
import type { SourceRegistry, InstalledSource } from "@/data/schema";
import type { CacheStore } from "@/data/cache";

/** Minimal interface for saving installed sources */
export interface InstalledSourceStore {
  saveInstalledSource(source: InstalledSource): Promise<void>;
}
import type { SourceRegistryProvider, RegistrySourceInfo } from "../registry";
import type { MangaSource } from "../types";
import type { ExtensionManifest } from "@nemu.pm/tachiyomi-runtime";
import { loadExtension, type LoadedExtension } from "@nemu.pm/tachiyomi-runtime/async";
import { createTachiyomiBrowsableSource, SOURCE_SELECTION_KEY } from "./adapter";
import { SERVICE_URL } from "@/config";
import { Keys } from "@/data/keys";
import { getSourceSettingsStore } from "@/stores/source-settings";
import { normalizeSourceLangs } from "../language";

export const TACHIYOMI_LOCAL_REGISTRY_ID = "tachiyomi-local";

interface LocalExtension {
  path: string; // e.g., "en/mangapill"
  manifest: ExtensionManifest;
  jsUrl: string;
  iconUrl?: string;
  loadedExtension?: LoadedExtension; // Cached loaded extension
}

/**
 * Local registry for locally built Tachiyomi extensions.
 * Only enabled in development mode (import.meta.env.DEV).
 */
export class TachiyomiLocalRegistry implements SourceRegistryProvider {
  readonly info: SourceRegistry = {
    id: TACHIYOMI_LOCAL_REGISTRY_ID,
    name: "Tachiyomi Local",
    type: "builtin",
  };

  private installedSourceStore: InstalledSourceStore;
  private cacheStore: CacheStore;
  private extensions = new Map<string, LocalExtension>();
  private loadedSources = new Map<string, MangaSource>();
  private initialized = false;

  constructor(installedSourceStore: InstalledSourceStore, cacheStore: CacheStore) {
    this.installedSourceStore = installedSourceStore;
    this.cacheStore = cacheStore;
  }

  /**
   * Update the installed source store (called when auth state changes)
   */
  setInstalledSourceStore(store: InstalledSourceStore): void {
    this.installedSourceStore = store;
  }

  /**
   * Update the cache store
   */
  setCacheStore(store: CacheStore): void {
    this.cacheStore = store;
  }

  /**
   * Scan local extensions directory for built extensions
   */
  async listSources(): Promise<RegistrySourceInfo[]> {
    await this.ensureInitialized();
    
    const results: RegistrySourceInfo[] = [];
    
    for (const [id, ext] of this.extensions) {
      const languages = normalizeSourceLangs([ext.manifest.lang]);
      results.push({
        id,
        name: ext.manifest.name,
        version: ext.manifest.version,
        icon: ext.iconUrl,
        languages: languages.length > 0 ? languages : undefined,
        hasAuthentication: ext.manifest.hasWebView,
        hasCloudflare: ext.manifest.hasCloudflare,
      });
    }
    
    return results;
  }

  private async ensureInitialized(): Promise<void> {
    if (this.initialized) return;
    
    try {
      // Fetch the index of available extensions (generated by vite plugin)
      const response = await fetch("/local-extensions/index.json");
      if (!response.ok) {
        console.log("[TachiyomiLocal] No local extensions available");
        this.initialized = true;
        return;
      }
      
      const extensionPaths: string[] = await response.json();
      console.log(`[TachiyomiLocal] Found ${extensionPaths.length} local extensions`);
      
      for (const extPath of extensionPaths) {
        try {
          const manifestRes = await fetch(`/local-extensions/${extPath}/manifest.json`);
          if (!manifestRes.ok) continue;
          
          const manifest: ExtensionManifest = await manifestRes.json();
          const jsUrl = `/local-extensions/${extPath}/${manifest.jsPath}`;
          const iconUrl = manifest.icon ? `/local-extensions/${extPath}/${manifest.icon}` : undefined;
          
          // Store extension info (sources loaded lazily via getSource)
          this.extensions.set(extPath, { path: extPath, manifest, jsUrl, iconUrl });
          
          console.log(`[TachiyomiLocal] Loaded ${manifest.name} (${extPath})`);
        } catch (e) {
          console.warn(`[TachiyomiLocal] Failed to load ${extPath}:`, e);
        }
      }
    } catch (e) {
      console.log("[TachiyomiLocal] Could not fetch index.json:", e);
    }
    
    this.initialized = true;
  }

  async installSource(sourceId: string): Promise<void> {
    await this.ensureInitialized();
    
    const ext = this.extensions.get(sourceId);
    if (!ext) {
      throw new Error(`Extension not found: ${sourceId}`);
    }
    
    // Save to installed source store so it appears in installed sources
    await this.installedSourceStore.saveInstalledSource({
      id: Keys.source(TACHIYOMI_LOCAL_REGISTRY_ID, sourceId),
      registryId: TACHIYOMI_LOCAL_REGISTRY_ID,
      version: ext.manifest.version,
    });
  }

  async isInstalled(sourceId: string): Promise<boolean> {
    await this.ensureInitialized();
    return this.extensions.has(sourceId);
  }

  async getSource(sourceId: string): Promise<MangaSource | null> {
    await this.ensureInitialized();
    
    // Check cache first
    const cached = this.loadedSources.get(sourceId);
    if (cached) return cached;

    const ext = this.extensions.get(sourceId);
    if (!ext) {
      console.warn(`[TachiyomiLocal] Extension not found: ${sourceId}`);
      return null;
    }

    try {
      const sourceKey = Keys.source(TACHIYOMI_LOCAL_REGISTRY_ID, sourceId);
      
      // Load extension if not already loaded
      if (!ext.loadedExtension) {
        ext.loadedExtension = await loadExtension(ext.jsUrl, ext.manifest, {
          proxyUrl: `${SERVICE_URL}/proxy?url=`,
        });
      }
      
      // Get sources from loaded extension
      const sources = ext.loadedExtension.sources;
      if (sources.length === 0) {
        throw new Error(`No sources in extension: ${ext.manifest.name}`);
      }
      
      // Determine which source to load
      const settingsStore = getSourceSettingsStore();
      await settingsStore.getState().initialize();
      const savedSettings = settingsStore.getState().values.get(sourceKey) ?? {};
      const savedSourceId = savedSettings[SOURCE_SELECTION_KEY] as string | undefined;
      
      let selectedSourceId: string;
      if (savedSourceId && sources.some(s => s.id === savedSourceId)) {
        selectedSourceId = savedSourceId;
      } else {
        const englishSource = sources.find(s => s.lang === "en");
        selectedSourceId = englishSource?.id ?? sources[0].id;
      }
      
      const asyncSource = ext.loadedExtension.getSource(selectedSourceId);
      const source = await createTachiyomiBrowsableSource(asyncSource, sourceKey, this.cacheStore);
      this.loadedSources.set(sourceId, source);
      
      console.log(`[TachiyomiLocal] Loaded source: ${source.name} (${selectedSourceId})`);
      return source;
    } catch (e) {
      console.error(`[TachiyomiLocal] Failed to load source ${sourceId}:`, e);
      return null;
    }
  }

  /**
   * Unload a source from the registry (disposes and clears cache)
   */
  unloadSource(sourceId: string): void {
    const source = this.loadedSources.get(sourceId);
    if (source) {
      source.dispose();
      this.loadedSources.delete(sourceId);
    }
  }

  /** Unload all loaded sources (safe to call during React Strict Mode) */
  unloadAll(): void {
    for (const source of this.loadedSources.values()) {
      source.dispose();
    }
    this.loadedSources.clear();
  }

  /**
   * Force reload extensions (useful for hot reload during dev)
   */
  async reload(): Promise<void> {
    this.unloadAll();
    this.extensions.clear();
    this.initialized = false;
    
    await this.ensureInitialized();
  }
}

