// Web Worker for running Keiyoushi (Tachiyomi) Kotlin/WASM sources
// Sync XHR works in workers, enabling blocking HTTP calls from WASM
import * as Comlink from "comlink";
import type {
  SourceInfo,
  MangaDto,
  ChapterDto,
  PageDto,
  MangasPageDto,
  KeiyoushiManifest,
} from "./types";

// Kotlin/WASM module exports (generated by extension-compiler)
interface KeiyoushiWasmExports {
  getSourceCount(): number;
  getSourceInfo(index: number): string; // JSON
  getSourceName(index: number): string;
  getSourceLang(index: number): string;
  getSourceId(index: number): string;
  getSourceBaseUrl(index: number): string;
  getPopularManga(index: number, page: number): string; // JSON MangasPageDto
  getLatestUpdates(index: number, page: number): string; // JSON MangasPageDto
  searchManga(index: number, page: number, query: string): string; // JSON MangasPageDto
  getMangaDetails(index: number, mangaUrl: string): string; // JSON MangaDto
  getChapterList(index: number, mangaUrl: string): string; // JSON ChapterDto[]
  getPageList(index: number, chapterUrl: string): string; // JSON PageDto[]
  getImageUrl(index: number, pageUrl: string): string;
  getImage(index: number, pageUrl: string, pageImageUrl: string): Promise<string>; // base64
}

class WorkerSource {
  private exports: KeiyoushiWasmExports | null = null;
  private sourceIndex = 0;
  private manifest: KeiyoushiManifest | null = null;

  async load(wasmUrl: string, manifest: KeiyoushiManifest): Promise<boolean> {
    try {
      console.log("[Keiyoushi Worker] Loading WASM from:", wasmUrl);
      this.manifest = manifest;

      // Kotlin/WASM uses ES modules - import the uninstantiated module
      const moduleUrl = wasmUrl.replace(".wasm", ".uninstantiated.mjs");
      const module = await import(/* @vite-ignore */ moduleUrl);
      
      // Get the wasm file path relative to the module
      const wasmPath = wasmUrl;
      
      // Instantiate with WASM file path
      const { exports } = await module.instantiate({ 
        "./": wasmPath.substring(0, wasmPath.lastIndexOf("/") + 1) 
      }, true);
      
      this.exports = exports as KeiyoushiWasmExports;
      
      const sourceCount = this.exports.getSourceCount();
      console.log("[Keiyoushi Worker] Loaded, source count:", sourceCount);
      
      return sourceCount > 0;
    } catch (e) {
      console.error("[Keiyoushi Worker] Failed to load:", e);
      return false;
    }
  }

  isLoaded(): boolean {
    return this.exports !== null;
  }

  getManifest(): KeiyoushiManifest | null {
    return this.manifest;
  }

  getSourceCount(): number {
    return this.exports?.getSourceCount() ?? 0;
  }

  getSourceInfo(index: number): SourceInfo | null {
    if (!this.exports) return null;
    try {
      const json = this.exports.getSourceInfo(index);
      return JSON.parse(json) as SourceInfo;
    } catch {
      return null;
    }
  }

  setSourceIndex(index: number): void {
    this.sourceIndex = index;
  }

  getPopularManga(page: number): MangasPageDto {
    if (!this.exports) return { mangas: [], hasNextPage: false };
    try {
      const json = this.exports.getPopularManga(this.sourceIndex, page);
      return JSON.parse(json) as MangasPageDto;
    } catch (e) {
      console.error("[Keiyoushi Worker] getPopularManga error:", e);
      return { mangas: [], hasNextPage: false };
    }
  }

  getLatestUpdates(page: number): MangasPageDto {
    if (!this.exports) return { mangas: [], hasNextPage: false };
    try {
      const json = this.exports.getLatestUpdates(this.sourceIndex, page);
      return JSON.parse(json) as MangasPageDto;
    } catch (e) {
      console.error("[Keiyoushi Worker] getLatestUpdates error:", e);
      return { mangas: [], hasNextPage: false };
    }
  }

  searchManga(page: number, query: string): MangasPageDto {
    if (!this.exports) return { mangas: [], hasNextPage: false };
    try {
      const json = this.exports.searchManga(this.sourceIndex, page, query);
      return JSON.parse(json) as MangasPageDto;
    } catch (e) {
      console.error("[Keiyoushi Worker] searchManga error:", e);
      return { mangas: [], hasNextPage: false };
    }
  }

  getMangaDetails(mangaUrl: string): MangaDto | null {
    if (!this.exports) return null;
    try {
      const json = this.exports.getMangaDetails(this.sourceIndex, mangaUrl);
      return JSON.parse(json) as MangaDto;
    } catch (e) {
      console.error("[Keiyoushi Worker] getMangaDetails error:", e);
      return null;
    }
  }

  getChapterList(mangaUrl: string): ChapterDto[] {
    if (!this.exports) return [];
    try {
      const json = this.exports.getChapterList(this.sourceIndex, mangaUrl);
      return JSON.parse(json) as ChapterDto[];
    } catch (e) {
      console.error("[Keiyoushi Worker] getChapterList error:", e);
      return [];
    }
  }

  getPageList(chapterUrl: string): PageDto[] {
    if (!this.exports) return [];
    try {
      const json = this.exports.getPageList(this.sourceIndex, chapterUrl);
      return JSON.parse(json) as PageDto[];
    } catch (e) {
      console.error("[Keiyoushi Worker] getPageList error:", e);
      return [];
    }
  }

  getImageUrl(pageUrl: string): string {
    if (!this.exports) return "";
    try {
      return this.exports.getImageUrl(this.sourceIndex, pageUrl);
    } catch (e) {
      console.error("[Keiyoushi Worker] getImageUrl error:", e);
      return "";
    }
  }

  async getImage(pageUrl: string, pageImageUrl: string): Promise<string> {
    if (!this.exports) return "";
    try {
      return await this.exports.getImage(this.sourceIndex, pageUrl, pageImageUrl);
    } catch (e) {
      console.error("[Keiyoushi Worker] getImage error:", e);
      return "";
    }
  }
}

const workerSource = new WorkerSource();
Comlink.expose(workerSource);

export type WorkerSourceApi = WorkerSource;

